version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_FRONTEND_URL=http://localhost:8080
    volumes:
      - ./keycloak:/opt/keycloak/data/
    command: start-dev
    networks:
      - keycloak
  
  backend:
    tty: true
    build:
      context: ./backend
      args:
        requirements: requirements/reqs.txt
    environment:
      # use in code
      - DEBUG=True
      - PYTHONUNBUFFERED=1
      - PORT=${PORT}
      - OPEN_ID_CLIENT_ID=${OPEN_ID_CLIENT_ID}
      - OPEN_ID_CLIENT_SECRET=${OPEN_ID_CLIENT_SECRET}
    restart: always
    volumes:
      - .:/app:delegated
    ports:
      - 8001:8001
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8001 --reload
    networks:
      - keycloak

networks:
  keycloak:
    driver: bridge